var gec_courses = {
	title : "Goa College of Engineering - Courses",
	courses : [
		"Applied Mathematics I",
		"Applied Science I",
		"Applied Mathematics II",
		"Applied Science II",
		"Information Technology",
		"Applied Mathematics III",
		"Basic of C++",
		"Principles of Programming Languages",
		"Computer Oriented Numerical Methods",
		"Logic Design",
		"Descrete Mathematical Structure",
		"Data Structures",
		"Computer Organization",
		"System Analysis and Design",
		"Object Oriented Programming & Design using C++",
		"Automata Languages and Computation",
		"Micorprocessors and Microcontrollers",
		"Computer Hardware Design",
		"Database Management System",
		"Operating System",
		"Modern Algorithm Design Foundation Theory",
		"Object Oriented Software Engineering",
		"Artificial Intelligence",
		"Computer Graphics",
		"Device Interface and PC Maintenance",
		"Data Communication",
		"Language Translators",
		"Computer Networks",
		"Digital Signal Processing",
		"Web Technologies",
		"Data Compression",
		"Advance Data Structures and Algorithms",
		"Computer Cryptography and Networks Security",
		"Web Services",
		"Mobile Computing"
	]
}